- name: Install MariaDB Repo
  apt_repository:
    repo: 'deb [arch=amd64,i386] http://mirror.23media.de/mariadb/repo/10.1/ubuntu trusty main'

- name: Add MariaDB Repository Key
  apt_key:
    state: 'present'
    keyserver: 'keyserver.ubuntu.com'
    id       : '0xcbcb082a1bb943db'

- name: Install MariaDB
  apt: name=mariadb-server state=latest update_cache=yes


