---

#- name: Install PHP Redis
#  pear:
#    name : 'redis'
#    state: 'present'
#
# php-redis module is still not compiled for php7 in Pear

- name: Install Php redis dev packages
  apt: name='{{ item }}'
  with_items: '{{ php_redis_packages }}'

- name: Clone php-redis git repository
  git:
    repo   : 'https://github.com/phpredis/phpredis.git'
    dest   : '/usr/src/phpredis'
    version: 'php7'

- name: Phpize
  command: '/usr/bin/phpize'
  args:
    chdir: '/usr/src/phpredis'

- name: Compile and install phpredis
  command: '{{ item }}'
  args:
    chdir: '/usr/src/phpredis'
  with_items:
    - ./configure
    - make
    - make install

- name: Copy redis.ini
  copy:
    src : 'files/redis.ini'
    dest: '/etc/php/7.0/mods-available'
    

- name: Enable PHP Redis module
  command: '/usr/sbin/phpenmod redis'
  notify: Restart php-fpm
